ifeq ($(TARGET_BOOTLOADER_BOARD_NAME),u8800pro)

LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

ifdef WIFI_DRIVER_MODULE_PATH
LOCAL_CFLAGS += -DWIFI_DRIVER_MODULE_PATH=\"$(WIFI_DRIVER_MODULE_PATH)\"
endif

ifdef WIFI_DRIVER_MODULE_ARG
LOCAL_CFLAGS += -DWIFI_DRIVER_MODULE_ARG=\"$(WIFI_DRIVER_MODULE_ARG)\"
endif

LOCAL_SRC_FILES := load_wifi.c
LOCAL_MODULE:= load_wifi
LOCAL_SHARED_LIBRARIES := libcutils libc libhwrpc
LOCAL_MODULE_TAGS := eng
include $(BUILD_EXECUTABLE)

endif # TARGET_BOOTLOADER_BOARD_NAME
