#!/bin/bash

export LOC="$PWD/out/target/product/u8800pro"
export Geno="$PWD"

mkdir -p "$LOC"/temp

cd "$LOC"/temp
echo "extract update.zip"
unzip -o -qq  "$LOC"/$TARGET_PRODUCT-ota-$TARGET_BUILD_VARIANT.$LOGNAME.zip

echo "Making U8800pro Compatible Update script"
cd "$LOC"
cd "$LOC"/temp/META-INF/com/google/android
grep -vw boot.img  updater-script > temp
echo 'mount("vfat", "EMMC", "/dev/block/mmcblk0p1", "/cust");' >> temp
echo 'package_extract_file("boot.img","/cust/image/boot.img");' >> temp
echo 'unmount("/cust");' >> temp
grep -vw assert  temp > updater-script
rm -rf temp
echo Zipping Package
cd "$LOC"/temp
rm -rf "$LOC"/temp/recovery
rm -rf "$LOC"/$TARGET_PRODUCT-ota-$TARGET_BUILD_VARIANT.$LOGNAME.zip
zip -9yr "$LOC"/$TARGET_PRODUCT-ota-$TARGET_BUILD_VARIANT.$LOGNAME.zip * > /dev/null
cd "$LOC"

echo Cleanup...
rm -rf "$LOC"/temp
sh $Geno/vendor/cyanogen/tools/squisher
echo done
